name: quiz_learn
description: A new Flutter project.

publish_to: 'none' 

environment:
  sdk: '>=2.18.5 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.1.4
  firebase_core: ^2.3.0
  get: ^4.6.5
  cloud_firestore: ^4.1.0
  firebase_messaging: ^14.1.2
  flutter_local_notifications: ^12.0.4
  firebase_analytics: ^10.0.6
  firebase_crashlytics: ^3.0.6
  uuid: ^3.0.7
  flutter_screenutil: ^5.6.0
  flutter_svg: ^1.1.6
  google_fonts: ^3.0.1
  firebase_storage: ^11.0.6
  lottie: ^2.0.0
  cached_network_image: ^3.2.3
  flutter_zoom_drawer: ^3.0.3
  url_launcher: ^6.1.7
  google_sign_in: ^5.4.2
  fluttertoast: ^8.1.1
  shimmer: ^2.0.0
  easy_separator: ^1.0.1
  flutter_launcher_icons: ^0.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_splash_logo.png"
  min_sdk_android: 21

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/DB/papers/

  fonts:
    - family: AppIcons
      fonts:
        - asset: assets/icons/AppIcons.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  
